//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdditionDatabaseEntities : DbContext
    {
        public AdditionDatabaseEntities()
            : base("name=AdditionDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Desk> Desks { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Waiter> Waiters { get; set; }
        public virtual DbSet<ProductsOfDesk> ProductsOfDesks { get; set; }
    }
}
