//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsOfDesk
    {
        public int Id { get; set; }
        public Nullable<int> DeskId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> WaiterId { get; set; }
        public Nullable<System.DateTime> ProcessDateTime { get; set; }
    
        public virtual Desk Desk { get; set; }
        public virtual Product Product { get; set; }
        public virtual Waiter Waiter { get; set; }
    }
}
