//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _PrsentationLayer.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Garson", Namespace="http://schemas.datacontract.org/2004/07/_DataLayer.Models")]
    [System.SerializableAttribute()]
    public partial class Garson : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoyadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ad {
            get {
                return this.AdField;
            }
            set {
                if ((object.ReferenceEquals(this.AdField, value) != true)) {
                    this.AdField = value;
                    this.RaisePropertyChanged("Ad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Soyad {
            get {
                return this.SoyadField;
            }
            set {
                if ((object.ReferenceEquals(this.SoyadField, value) != true)) {
                    this.SoyadField = value;
                    this.RaisePropertyChanged("Soyad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Masa", Namespace="http://schemas.datacontract.org/2004/07/_DataLayer.Models")]
    [System.SerializableAttribute()]
    public partial class Masa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MasaAdiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MasaAdi {
            get {
                return this.MasaAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.MasaAdiField, value) != true)) {
                    this.MasaAdiField = value;
                    this.RaisePropertyChanged("MasaAdi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IAdditionService")]
    public interface IAdditionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdditionService/GetGarson", ReplyAction="http://tempuri.org/IAdditionService/GetGarsonResponse")]
        _PrsentationLayer.ServiceReference.Garson GetGarson(string u, string p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdditionService/GetGarson", ReplyAction="http://tempuri.org/IAdditionService/GetGarsonResponse")]
        System.Threading.Tasks.Task<_PrsentationLayer.ServiceReference.Garson> GetGarsonAsync(string u, string p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdditionService/Masalar", ReplyAction="http://tempuri.org/IAdditionService/MasalarResponse")]
        _PrsentationLayer.ServiceReference.Masa[] Masalar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdditionService/Masalar", ReplyAction="http://tempuri.org/IAdditionService/MasalarResponse")]
        System.Threading.Tasks.Task<_PrsentationLayer.ServiceReference.Masa[]> MasalarAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdditionServiceChannel : _PrsentationLayer.ServiceReference.IAdditionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdditionServiceClient : System.ServiceModel.ClientBase<_PrsentationLayer.ServiceReference.IAdditionService>, _PrsentationLayer.ServiceReference.IAdditionService {
        
        public AdditionServiceClient() {
        }
        
        public AdditionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdditionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdditionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdditionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public _PrsentationLayer.ServiceReference.Garson GetGarson(string u, string p) {
            return base.Channel.GetGarson(u, p);
        }
        
        public System.Threading.Tasks.Task<_PrsentationLayer.ServiceReference.Garson> GetGarsonAsync(string u, string p) {
            return base.Channel.GetGarsonAsync(u, p);
        }
        
        public _PrsentationLayer.ServiceReference.Masa[] Masalar() {
            return base.Channel.Masalar();
        }
        
        public System.Threading.Tasks.Task<_PrsentationLayer.ServiceReference.Masa[]> MasalarAsync() {
            return base.Channel.MasalarAsync();
        }
    }
}
